export interface ScheduleRow {
  time: string;
  lundi: string;
  mardi: string;
  mercredi: string;
  jeudi: string;
  vendredi: string;
  samedi: string;
  dimanche: string;
}

export const schedule: ScheduleRow[] = [
  {
    time: "6H - 7H",
    lundi: "Animation",
    mardi: "Animation libre",
    mercredi: "Animation libre",
    jeudi: "Animation libre",
    vendredi: "Animation libre",
    samedi: "Animation libre",
    dimanche: "Animation libre",
  },
  {
    time: "7H - 8H",
    lundi: "Disons-nous la vérité",
    mardi: "Disons-nous la vérité",
    mercredi: "Disons-nous la vérité",
    jeudi: "Disons-nous la vérité",
    vendredi: "Disons-nous la vérité",
    samedi: "Parole d’Evangile",
    dimanche: "Emission Catholique",
  },
  {
    time: "8H - 8H30",
    lundi: "Journal Parlé",
    mardi: "Journal Parlé",
    mercredi: "Journal Parlé",
    jeudi: "Journal Parlé",
    vendredi: "Journal Parlé",
    samedi: "Journal Parlé",
    dimanche: "Journal Parlé",
  },
  {
    time: "8H30 - 10H",
    lundi: "Bâté Guinet",
    mardi: "Bâté Guinet",
    mercredi: "Bâté Guinet",
    jeudi: "Questions et réponses",
    vendredi: "Musique Sénégal",
    samedi: "Animation afrobeats",
    dimanche: "Islam en français",
  },
  {
    time: "10H - 11H",
    lundi: "Libre antenne",
    mardi: "Libre antenne",
    mercredi: "Libre antenne",
    jeudi: "Libre antenne",
    vendredi: "Sanakouya",
    samedi: "Face à l’actualité",
    dimanche: "L’artiste de la semaine",
  },
  {
    time: "11H - 12H",
    lundi: "Musique",
    mardi: "Musique",
    mercredi: "Musique",
    jeudi: "Ma santéya",
    vendredi: "Sanakouya",
    samedi: "Face à l’actualité",
    dimanche: "Musique",
  },
  {
    time: "12H - 13H",
    lundi: "Horizon Sport",
    mardi: "Musique",
    mercredi: "Musique",
    jeudi: "Musique",
    vendredi: "Musique",
    samedi: "Musique",
    dimanche: "Musique",
  },
  {
    time: "13H - 13H30",
    lundi: "Journal parlé",
    mardi: "Journal parlé",
    mercredi: "Journal parlé",
    jeudi: "Journal parlé",
    vendredi: "Journal parlé",
    samedi: "Journal parlé",
    dimanche: "Journal en Soussou",
  },
  {
    time: "13H30 - 14H",
    lundi: "-",
    mardi: "Musique",
    mercredi: "Musique",
    jeudi: "Musique",
    vendredi: "Coran",
    samedi: "Musique",
    dimanche: "Musique",
  },
  {
    time: "14H - 15H",
    lundi: "Nakhan Kolon",
    mardi: "Nakhan Kolon",
    mercredi: "Comédie",
    jeudi: "Ma Guinée d’ab",
    vendredi: "Musique",
    samedi: "Environnement",
    dimanche: "Musique",
  },
  {
    time: "15H - 15H30",
    lundi: "Nakhan Kolon (Suite)",
    mardi: "Nakhan Kolon (Suite)",
    mercredi: "Emission Timbo",
    jeudi: "Musique",
    vendredi: "Gandal Islam Soussou",
    samedi: "Gandal Islam Poular",
    dimanche: "Disque des auditeurs",
  },
  {
    time: "15H30 - 16H",
    lundi: "Gandal Islam Malinké",
    mardi: "Focus du jour",
    mercredi: "Emission Timbo Suite",
    jeudi: "Gandal Islam",
    vendredi: "Gandal Islam Soussou",
    samedi: "Gandal Islam Poular",
    dimanche: "Disque des auditeurs",
  },
  {
    time: "16H - 16H30",
    lundi: "Journal parlé",
    mardi: "Journal parlé",
    mercredi: "Journal parlé",
    jeudi: "Journal parlé",
    vendredi: "Journal parlé",
    samedi: "Journal parlé",
    dimanche: "Journal en Soussou",
  },
  {
    time: "16H30 - 17H",
    lundi: "Gandal Islam Malinké",
    mardi: "Gandal Islam Poular",
    mercredi: "Reggae Vibes",
    jeudi: "Gandal Islam Malinké",
    vendredi: "Horizon Sport",
    samedi: "High Tech",
    dimanche: "Horizon Sport",
  },
  {
    time: "17H - 18H",
    lundi: "Café des artistes",
    mardi: "Gandal Islam Poular",
    mercredi: "-",
    jeudi: "-",
    vendredi: "Horizon Sport",
    samedi: "Canal Mix",
    dimanche: "Horizon Sport",
  },
  {
    time: "18H - 18H30",
    lundi: "Journal",
    mardi: "Journal",
    mercredi: "Journal",
    jeudi: "Journal",
    vendredi: "Journal",
    samedi: "Journal",
    dimanche: "Musique",
  },
  {
    time: "19H - 20H",
    lundi: "Libre antenne",
    mardi: "Libre antenne",
    mercredi: "Libre antenne",
    jeudi: "Libre antenne",
    vendredi: "Musique",
    samedi: "Latino",
    dimanche: "J’ai une idée",
  },
  {
    time: "20H - 20H15",
    lundi: "Journal parlé",
    mardi: "Journal Parlé",
    mercredi: "Journal parlé",
    jeudi: "Journal parlé",
    vendredi: "Journal parlé",
    samedi: "Journal parlé",
    dimanche: "Musique",
  },
  {
    time: "20H30 - 21H",
    lundi: "Batè Guinè Rediff",
    mardi: "Nakhan Kolon Rediff",
    mercredi: "Musique",
    jeudi: "Musique",
    vendredi: "Cour des Grands",
    samedi: "Musique",
    dimanche: "Musique",
  },
  {
    time: "21H30 - 22H",
    lundi: "Batè Guinè Rediff",
    mardi: "Nakhan Kolon Rediff",
    mercredi: "Batè Guinè Rediff",
    jeudi: "-",
    vendredi: "ZIk Horizon",
    samedi: "Musique",
    dimanche: "Face à l’actualité",
  },
  {
    time: "22H - 22H30",
    lundi: "Journal parlé",
    mardi: "Journal parlé",
    mercredi: "Journal parlé",
    jeudi: "Journal parlé",
    vendredi: "Journal parlé",
    samedi: "Journal parlé",
    dimanche: "Suite",
  },
  {
    time: "22H30 - 23H",
    lundi: "High Tech",
    mardi: "High Tech",
    mercredi: "High Tech",
    jeudi: "High Tech",
    vendredi: "High Tech",
    samedi: "Maxi Music",
    dimanche: "Face à l’actualité",
  },
  {
    time: "23H - 00H",
    lundi: "Disons-nous la vérité",
    mardi: "Disons-nous la vérité",
    mercredi: "Jeu de drague",
    jeudi: "Disons-nous la vérité",
    vendredi: "Disons-nous la vérité",
    samedi: "Jeu de drague",
    dimanche: "Animation",
  },
];
